### PR TITLE
Feature/automation

### PR DESCRIPTION
**Pull request by andytson**
Includes:
- standard cookbook style checks (rubocop currently not passing)
- scafolding for chefspec tests
- kitchen integration tests that verify mailcatcher functioning for CentOS 6 and 7
- Travis CI configuration ready for hooking into Travis CI (excludes integration tests because can't use VMs within VMs)
- Stove for easy publishing to supermarket.chef.io (see https://github.com/inviqa/chef-config-driven-helper#supermarket-share for an example on how to use it)

### CODE REVIEW

**Comment by elvetemedve** [comment]
http://weknowmemes.com/wp-content/uploads/2011/12/i-have-no-idea-what-im-doing1.jpg

**Comment by andytson** [comment]
Thanks @elvetemedve, is it possible you could add this repository to TravisCI https://travis-ci.org/elvetemedve/mailcatcher ?

**Comment by elvetemedve** [comment]
@andytson I've added the repo to Travis CI, and put the build status indicator into the Readme file.

**Comment by andytson** [comment]
great, thanks, new PRs will automatically be CI'd now then, assuming Travis CI pushed the webhook through on https://github.com/elvetemedve/mailcatcher/settings/hooks

**Comment by elvetemedve** [comment]
The CI build was triggered automatically when I pushed the changes of Readme.md to git.
Webhooks section is empty, do you want me to set up something there?

**Pull request merged**
